#' Wrapper Function - QAQC for Norovirus G1 & G2 results
#'
#' This function is meant to run a standard QAQC set-up using the functions available
#' in this package. For increased flexibility, manual construction of the functions
#' would be necessary
#'
#' This function returns a list where the first element is the processed dataframe
#' containing unmerged Sample-Target data points along with additional columns
#' generated by the processing minor functions, and the second element is an
#' error stop notification dataframe that is generated if hard stop notifications
#' are not used.
#'
#' @param data_frame_in A dataframe of laboratory data.
#' @param lab_site_ids A character string vector for w0150_sample_naming_structure (A character string vector identifying the submitter sites)
#' @param control_strings A vector of character strings for w0125_expected_controls_present (A vector of character strings that indicate control wells) and w0150_sample_naming_structure (A vector of character strings contained in control sample names)
#' @param pos_rows A Sample-Target dataframe of character strings for w0400 and w0450
#' @param con_rows A Sample-Target dataframe of character strings for w0700 and w0750
#' @param rules A vector of numbers indicating what rules to remove violators from (w1000)
#' @return A list where the first element is the dataframe containing unmerged Sample-Target data points, and the second element is an error stop notification dataframe that is generated if hard stop notifications are not used
#' @export

qaqc_processing_norog1g2 <- function(file_in, lab_site_ids,
                                     control_strings = c("NEG", "POS", "NTC", "EXT"),
                                     pos_rows = data.frame(Samples = c("POS", "POS"),
                                                           Targets = c("NVG1", "NVG2")),
                                     con_rows = data.frame(Samples = c("NEG", "POS", "NTC", "NEG", "POS", "NTC"),
                                                           Targets = c("NVG1", "NVG1", "NVG1","NVG2", "NVG2", "NVG2")),

                                     rules = c(2, 3, 6)){

  file_in <- w0110_sample_name_edits(file_in)

  file_in <- w0125_expected_controls_present(file_in,
                                             control_strings,
                                             c(12, 12, 12, 0))

  error_line <- c("w0125")
  error_val <- c(file_in[2][[1]])

  file_in <- w0150_sample_naming_structure(file_in[1][[1]],
                                           lab_site_ids,
                                           control_strings)

  error_line <- c(error_line, "w0150")
  error_val <- c(error_val, file_in[2][[1]])

  file_in <- w0200_accepted_droplet_count(file_in[1][[1]])

  file_in <- w0300_ntc_control_check(file_in)

  error_line <- c(error_line, "w0300")
  error_val <- c(error_val, file_in[2][[1]])

  error_line <- c(error_line, "w0400")
  error_val <- c(error_val, w0400_pos_control_hard_stop(file_in[1][[1]], pos_rows))
  # just a check, no return value

  file_in <- w0450_pos_control_breakdown_check(file_in[1][[1]], pos_rows, 35)

  file_in <- w0600_ext_neg_control_check(file_in, 9, 3, 3, 1)

  error_line <- c(error_line, "w0600")
  error_val <- c(error_val, file_in[2][[1]])

  error_line <- c(error_line, "w0650")
  error_val <- c(error_val, w0650_cumulative_count_check(file_in[1][[1]], 3, "no"))

  file_in <- w0700_pos_droplet_sum(file_in[1][[1]], controls_to_drop = con_rows)

  file_in <- w0750_neg_droplet_samples(file_in, controls_to_drop = con_rows)
  error_line <- c(error_line, "w0750")
  error_val <- c(error_val, file_in[2][[1]])

  file_in <- w0900_positives_comparison_rule(file_in[1][[1]], c("POS"), c("NVG1", "NVG2"), control_strings, 3)

  file_in <- w1000_remove_rows_as_chosen(file_in, rules)

  error_df <- data.frame(error_line, error_val)

  message("End wrapper for Noro G1 & G2.")

  return(list(file_in, error_df))

}

