
#' Wrapper Function - QAQC for SARS-CoV-2 N1 Testing
#'
#' This function is meant to run a standard QAQC set-up using the functions available
#' in this package. For increased flexibility, manual construction of the functions
#' would be necessary
#'
#' The default settings of expected count are for the assumption of pmmov & bcov testing
#' within the sars-cov-2 n1 testing (so, two plates) with expected controls of:
#'
#' | Sample | Target | Count Wells |
#' | --- | --- | --- |
#' | BCOV | PMMOV | 3 |
#' | BCOV | BCOV | 3 |
#' | EXT | PMMOV | 3 |
#' | EXT | BCOV | 3 |
#' | NEG | PMMOV | 3 |
#' | NEG | BCOV | 3 |
#' | NTC | PMMOV | 3 |
#' | NTC | BCOV | 3 |
#' | NEG | N1 | 3 |
#' | EXT | N1 | 3 |
#' | NTC | N1 | 3 |
#' | POS | N1 | 3 |
#'
#' This function returns a list where the first element is the processed dataframe
#' containing unmerged Sample-Target data points along with additional columns
#' generated by the processing minor functions, and the second element is an
#' error stop notification dataframe that is generated if hard stop notifications
#' are not used.
#'
#' @param file_in A dataframe of laboratory data.
#' @param lab_site_ids A character string vector for w0150_sample_naming_structure (A character string vector identifying the submitter sites)
#' @param targets_to_keep A vector of character strings indicating the Target values the user would like to allow (w0115)
#' @param control_strings A vector of character strings for w0125_expected_controls_present (A vector of character strings that indicate control wells) and w0150_sample_naming_structure (A vector of character strings contained in control sample names)
#' @param expected_count A numeric vector of the expected number of wells for each control type. Default vector is 3, 3, 3, 3, 3.
#' @param pos_rows A Sample-Target dataframe of character strings for w0400 and w0450
#' @param con_rows A Sample-Target dataframe of character strings for w0500, w0700, w0750
#' @param recover_unit A character string indicating the recovery control being used; default is BCOV
#' @param control_opts_two A vector of two control types that should be checked for negativity for w0600, default is c("EXT", "NEG")
#' @return A list where the first element is the dataframe containing unmerged Sample-Target data points, and the second element is an error stop notification dataframe that is generated if hard stop notifications are not used
#' @export

qaqc_processing_sc2_n1 <- function(file_in,
                                   lab_site_ids,
                                   targets_to_keep = c("N1", "BCOV"),
                control_strings = c("NEG", "POS", "NTC", "BCOV", "EXT"),
                expected_count = c(3, 3, 3, 3, 3),
                pos_rows = data.frame(Samples = c("POS", "BCOV"),
                                       Targets = c("N1", "BCOV")),
                con_rows = data.frame(Samples = c("BCOV", "BCOV", "POS", "EXT", "EXT","EXT","NEG","NEG","NEG", "NTC", "NTC", "NTC"),
                                       Targets = c("PMMOV", "BCOV",  "N1", "PMMOV", "N1", "BCOV", "PMMOV", "N1", "BCOV", "PMMOV", "N1", "BCOV")),
                recover_unit = "BCOV",
                control_opts_two = c("EXT", "NEG")
                ){

  file_in <- w0110_sample_name_edits(file_in)

  file_in <- w0115_target_check(file_in, targets_to_keep)
  error_line <- c("w0115")
  error_val <- c(file_in[2][[1]])

  if (file_in[2][[1]] == 0){

      file_in <- w0125_expected_controls_present(file_in[1][[1]],
                                                control_strings,
                                                expected_count)

      error_line <- c("w0125")
      error_val <- c(file_in[2][[1]])

      file_in <- w0150_sample_naming_structure(file_in[1][[1]],
                                             lab_site_ids,
                                             control_strings)

      error_line <- c(error_line, "w0150")
      error_val <- c(error_val, file_in[2][[1]])

      file_in <- w0200_accepted_droplet_count(file_in[1][[1]])

      file_in <- w0300_ntc_control_check(file_in)
      error_line <- c(error_line, "w0300")
      error_val <- c(error_val, file_in[2][[1]])

      error_line <- c(error_line, "w0400")
      error_val <- c(error_val, w0400_pos_control_hard_stop(file_in[1][[1]], pos_rows))


      file_in <- w0450_pos_control_breakdown_check(file_in[1][[1]], pos_rows, 35)

      file_in <- w0500_control_soft_check(file_in, con_rows)

      file_in <- w0600_ext_neg_control_check(file_in, control_opts_two, recover_unit,
                                             positive_droplet = 3,
                                             wells_over = 1)

      error_line <- c(error_line, "w0600")
      error_val <- c(error_val, file_in[2][[1]])

      error_line <- c(error_line, "w0650")
      error_val <- c(error_val, w0650_cumulative_count_check(file_in[1][[1]], 3, "no"))

      file_in <- w0700_pos_droplet_sum(file_in[1][[1]], controls_to_drop = con_rows)

      file_in <- w0750_neg_droplet_samples(file_in, controls_to_drop = con_rows)
      error_line <- c(error_line, "w0750")
      error_val <- c(error_val, file_in[2][[1]])

      file_in <- w0800_recover_control_check(file_in[1][[1]], recover_unit, control_strings, 0.3)

      file_in <- w0900_positives_comparison_rule(file_in, pos_rows[, 1], pos_rows[, 2], control_strings, 3)

      file_in <- w1000_remove_rows_as_chosen(file_in)

      error_df <- data.frame(error_line, error_val)

      message("End wrapper for SARS-CoV-2 N1")

  } else {

      error_df <- data.frame(error_line, error_val)

      message("SARS-CoV-2 N1  - Error with Targets listed & encountered - Stop Error #1.15")

  }

  return(list(file_in, error_df))

}

