#' Wrapper Function - QAQC for Measles Duplex
#'
#' This function is meant to run a standard QAQC set-up using the functions available
#' in this package. For increased flexibility, manual construction of the functions
#' would be necessary
#'
#' This function returns a list where the first element is the processed dataframe
#' containing unmerged Sample-Target data points along with additional columns
#' generated by the processing minor functions, and the second element is an
#' error stop notification dataframe that is generated if hard stop notifications
#' are not used.

#' @param file_in Dataframe of laboratory data
#' @param lab_site_ids A character string vector for w0150 (A character string vector identifying the submitter sites)
#' @param targets_to_keep A vector of character strings indicating the Target values the user would like to allow (w0115)
#' @param control_strings A vector of character strings for w0125 and w0150
#' @param expected_count A numeric vector of the expected number of wells for each control type.
#' @param pos_rows A Sample-Target dataframe of character strings for w0450 and w0500 (indicating controlst that should be positive)
#' @param neg_rows A Sample-Target dataframe of character strings for w0550 (indicating controls that should be negative)
#' @param con_rows A Sample-Target dataframe of character strings for w0700 (indicating all controls)
#' @return A list where the first element is the dataframe containing unmerged Sample-Target data points, and the second element is an error stop notification dataframe that is generated if hard stop notifications are not used
#' @export
#'
qaqc_processing_measles_duplex <- function(file_in,
                                   lab_site_ids,
                                   targets_to_keep = c("MEVN3DEGEN", "MEVAMR"),
                                   control_strings = c("NEG", "POS", "NTC"),
                                   expected_count = c(16, 8, 8),
                                   pos_rows = data.frame(Samples = c("POS", "POS"),
                                                         Targets = c("MEVN3DEGEN", "MEVAMR")),
                                   neg_rows = data.frame(Samples = c("NEG", "NEG", "NTC", "NTC"),
                                                         Targets = c("MEVN3DEGEN", "MEVAMR", "MEVN3DEGEN", "MEVAMR")),
                                   con_rows = data.frame(Samples = rep(c("NEG", "POS", "NTC"), 2),
                                                         Targets = c(rep("MEVN3DEGEN", 3), rep("MEVAMR", 3)))
                                   ){

  meas1 <- w0110_sample_name_edits(file_in)

  meas1 <- w0115_target_check(meas1, targets_to_keep)
  error_line <- c("w0115")
  error_val <- c(meas1[2][[1]])

  if (meas1[2][[1]] == 0){

    meas1 <- w0125_expected_controls_present(meas1[1][[1]],
                                               control_strings,
                                               expected_count)

    error_line <- c("w0125")
    error_val <- c(meas1[2][[1]])

    # e track
    meas1 <- w0150_sample_naming_structure(meas1[1][[1]],
                                              lab_site_ids,
                                              control_strings)

    error_line <- c("w0150")
    error_val <- c(meas1[2][[1]])

    meas1 <- w0200_accepted_droplet_count(meas1[1][[1]], 10000)

    # e track
    meas1 <- w0300_ntc_control_check(meas1)

    error_line <- c(error_line, "w0300")
    error_val <- c(error_val, meas1[2][[1]])

    # e track
    meas1 <- w0400_pos_control_hard_stop(meas1[1][[1]], pos_rows)

    error_line <- c(error_line, "w0400")
    error_val <- c(error_val, meas1[2][[1]])


    meas1 <- w0450_pos_control_breakdown_check(meas1[1][[1]], pos_rows, limit_number = 100)

    meas1 <- w0550_negvalue_control_check(meas1,
                                          con_rows,
                                          pos_drop_limit = 2)

    error_line <- c(error_line, "w0550")
    error_val <- c(error_val, meas1[2][[1]])

    # e track
    error_line <- c(error_line, "w0650")
    error_val <- c(error_val, w0650_cumulative_count_check(meas1[1][[1]]))

    meas1 <- w0700_pos_droplet_sum(meas1[1][[1]], 4, con_rows)

    meas1 <- w1000_remove_rows_as_chosen(meas1, c(2, 3, 4, 5.5))

    error_df <- data.frame(error_line, error_val)

    message("End wrapper for Measles - Duplex")

    return(list(meas1, error_df))

  } else {

    error_df <- data.frame(error_line, error_val)

    message("Measles Duplex - Error with Targets listed & encountered - Stop Error #1.15")

    return(list(meas1[1][[1]], error_df))

  }

}
