
#' Wrapper Function - QAQC for SARS-CoV-2 N1 Testing
#'
#' This function is meant to run a standard QAQC set-up using the functions available
#' in this package. For increased flexibility, manual construction of the functions
#' would be necessary
#'
#' The default settings of expected count are for the assumption of pmmov & bcov testing
#' within the sars-cov-2 n1 testing (so, two plates) with expected controls of:
#'
#' | Sample | Target | Count Wells |
#' | --- | --- | --- |
#' | BCOV | PMMOV | 3 |
#' | BCOV | BCOV | 3 |
#' | EXT | PMMOV | 3 |
#' | EXT | BCOV | 3 |
#' | NEG | PMMOV | 3 |
#' | NEG | BCOV | 3 |
#' | NTC | PMMOV | 3 |
#' | NTC | BCOV | 3 |
#' | NEG | N1 | 3 |
#' | EXT | N1 | 3 |
#' | NTC | N1 | 3 |
#' | POS | N1 | 3 |
#'
#' This function returns a list where the first element is the processed dataframe
#' containing unmerged Sample-Target data points along with additional columns
#' generated by the processing minor functions, and the second element is an
#' error stop notification dataframe that is generated if hard stop notifications
#' are not used.
#'
#' @param data_frame_in A dataframe of laboratory data.
#' @param control_strings A vector of character strings for w0125_expected_controls_present (A vector of character strings that indicate control wells) and w0150_sample_naming_structure (A vector of character strings contained in control sample names)
#' @param expected_count A numeric vector of the expected number of wells for each control type. Default vector is 9, 3, 9, 6, 9.
#' @param pos_rows A Sample-Target dataframe of character strings for w0450_pos_control_breakdown_check
#' @param con_rows A Sample-Target dataframe of character strings for w0500_control_soft_check
#' @param lab_site_ids A character string vector for w0150_sample_naming_structure (A character string vector identifying the submitter sites)
#' @return A list where the first element is the dataframe containing unmerged Sample-Target data points, and the second element is an error stop notification dataframe that is generated if hard stop notifications are not used
#' @export

qaqc_processing_sc2_n1 <- function(file_in,
                control_strings = c("NEG", "POS", "NTC", "BCOV", "EXT"),
                expected_count = c(9, 3, 9, 6, 9),
                pos_rows = data.frame(Samples = c("POS", "BCOV"),
                                       Targets = c("N1", "BCOV")),
                con_rows = data.frame(Samples = c("BCOV"),
                                       Targets = c("PMMOV")),
                lab_site_ids){

  file_in <- w0110_sample_name_edits(file_in)

  file_in <- w0125_expected_controls_present(file_in,
                                            control_strings,
                                            expected_count)

  error_line <- c("w0125")
  error_val <- c(file_in[2][[1]])

  file_in <- w0150_sample_naming_structure(file_in[1][[1]],
                                         lab_site_ids,
                                         control_strings)

  error_line <- c(error_line, "w0150")
  error_val <- c(error_val, file_in[2][[1]])

  file_in <- w0200_accepted_droplet_count(file_in[1][[1]])

  file_in <- w0300_ntc_control_check(file_in)
  error_line <- c(error_line, "w0300")
  error_val <- c(error_val, file_in[2][[1]])

  error_line <- c(error_line, "w0400")
  error_val <- c(error_val, w0400_pos_control_hard_stop(file_in[1][[1]], pos_rows))


  file_in <- w0450_pos_control_breakdown_check(file_in[1][[1]], pos_rows, 35)

  file_in <- w0500_control_soft_check(file_in, con_rows)

  file_in <- w0600_ext_neg_control_check(file_in, 3, 3, 3, 1)

  error_line <- c(error_line, "w0600")
  error_val <- c(error_val, file_in[2][[1]])

  error_line <- c(error_line, "w0650")
  error_val <- c(error_val, w0650_cumulative_count_check(file_in[1][[1]], 3, "yes"))

  file_in <- w0800_recover_control_check(file_in[1][[1]], "BCOV", c("POS", "NEG", "EXT", "NTC"), 0.3)

  file_in <- w0900_positives_comparison_rule(file_in, c("POS"), c("N1"), c("POS", "NEG", "EXT", "NTC"), 3)

  file_in <- w1000_remove_rows_as_chosen(file_in)

  error_df <- data.frame(error_line, error_val)

  message("End wrapper for SARS-CoV-2 N1")

  return(list(file_in, error_df))

}

