#' Wrapper Function - QAQC for a Fiveplex
#'
#' This function is meant to run a standard QAQC set-up using the functions available
#' in this package. For increased flexibility, manual construction of the functions
#' would be necessary
#'
#' This function returns a list where the first element is the processed dataframe
#' containing unmerged Sample-Target data points along with additional columns
#' generated by the processing minor functions, and the second element is an
#' error stop notification dataframe that is generated if hard stop notifications
#' are not used.
#'
#' @param file_in A dataframe of laboratory data.
#' @param lab_site_ids A character string vector for w0150_sample_naming_structure (A character string vector identifying the submitter sites)
#' @param targets_to_keep A vector of character strings indicating the Target values the user would like to allow (w0115)
#' @param control_strings A vector of character strings for w0125_expected_controls_present (A vector of character strings that indicate control wells) and w0150_sample_naming_structure (A vector of character strings contained in control sample names)
#' @param pos_rows A Sample-Target dataframe of character strings for w0450 and w0500
#' @param con_rows A Sample-Target dataframe of character strings for w0700 and w0750
#' @return A list where the first element is the dataframe containing unmerged Sample-Target data points, and the second element is an error stop notification dataframe that is generated if hard stop notifications are not used
#' @export

qaqc_processing_fiveplex <- function(file_in,
                                     lab_site_ids,
                                     targets_to_keep = c("FluA", "FluB", "RSV", "SC2", "H5"),
                                   control_strings = c("NEG", "POS", "NTC", "EXT"),
                                   pos_rows = data.frame(Samples = c("POS", "POS", "POS", "POS", "POS"),
                                                         Targets = c("FluA", "FluB", "RSV", "SC2", "H5")),
                                   con_rows = data.frame(Samples = c("NEG", "POS", "NTC", "NEG", "POS", "NTC", "NEG", "POS", "NTC", "NEG", "POS", "NTC", "NEG", "POS", "NTC"),
                                                         Targets = c("FluA", "FluA", "FluA","FluB", "FluB", "FluB","RSV","RSV","RSV", "SC2", "SC2","SC2","H5","H5","H5"))
                                   ){

  file_in <- w0110_sample_name_edits(file_in)


  file_in <- w0115_target_check(file_in, targets_to_keep)
  error_line <- c("w0115")
  error_val <- c(file_in[2][[1]])

  if (file_in[2][[1]] == 0){

      file_in <- w0125_expected_controls_present(file_in[1][[1]],
                                                 control_strings,
                                                 c(12, 12, 12, 0))

      error_line <- c("w0125")
      error_val <- c(file_in[2][[1]])

      file_in <- w0150_sample_naming_structure(file_in[1][[1]],
                                               lab_site_ids,
                                               control_strings)

      error_line <- c(error_line, "w0150")
      error_val <- c(error_val, file_in[2][[1]])

      file_in <- w0200_accepted_droplet_count(file_in[1][[1]])

      file_in <- w0300_ntc_control_check(file_in)

      error_line <- c(error_line, "w0300")
      error_val <- c(error_val, file_in[2][[1]])

      error_line <- c(error_line, "w0400")
      error_val <- c(error_val, w0400_pos_control_hard_stop(file_in[1][[1]], pos_rows))
      # just a check, no return value

      file_in <- w0450_pos_control_breakdown_check(file_in[1][[1]], pos_rows, 35)

      file_in <- w0500_control_soft_check(file_in, pos_rows)

      file_in <- w0600_ext_neg_control_check(file_in, 9, 3, 3, 1)

      error_line <- c(error_line, "w0600")
      error_val <- c(error_val, file_in[2][[1]])

      error_line <- c(error_line, "w0650")
      error_val <- c(error_val, w0650_cumulative_count_check(file_in[1][[1]], 3, "no"))

      file_in <- w0700_pos_droplet_sum(file_in[1][[1]], controls_to_drop = con_rows)

      file_in <- w0750_neg_droplet_samples(file_in, controls_to_drop = con_rows)
      error_line <- c(error_line, "w0750")
      error_val <- c(error_val, file_in[2][[1]])

      file_in <- w0900_positives_comparison_rule(file_in[1][[1]], pos_rows[, 1], pos_rows[, 2], control_strings, 3)

      file_in <- w1000_remove_rows_as_chosen(file_in)

      error_df <- data.frame(error_line, error_val)

      message("End wrapper for FivePlex.")

  } else {

      error_df <- data.frame(error_line, error_val)

      message("FivePlex  - Error with Targets listed & encountered - Stop Error #1.15")

  }

  return(list(file_in, error_df))

}

