
#' Wrapper Function - QAQC for C. auris Testing
#'
#' This function is meant to run a standard QAQC set-up using the functions available
#' in this package. For increased flexibility, manual construction of the functions
#' would be necessary
#'
#' This function returns a list where the first element is the processed dataframe
#' containing unmerged Sample-Target data points along with additional columns
#' generated by the processing minor functions, and the second element is an
#' error stop notification dataframe that is generated if hard stop notifications
#' are not used.
#'
#' @param file_in A dataframe of laboratory data.
#' @param lab_site_ids A character string vector for w0150_sample_naming_structure (A character string vector identifying the submitter sites)
#' @param control_strings A vector of character strings for w0125_expected_controls_present (A vector of character strings that indicate control wells) and w0150_sample_naming_structure (A vector of character strings contained in control sample names)
#' @param pos_rows A Sample-Target dataframe of character strings for w0450_pos_control_breakdown_check
#' @param con_rows A Sample-Target dataframe of character strings for w0500_control_soft_check
#' @param e_w_c A numeric value indicating the number of EXT wells to expect, for use in w0600
#' @return A list where the first element is the dataframe containing unmerged Sample-Target data points, and the second element is an error stop notification dataframe that is generated if hard stop notifications are not used
#' @export

qaqc_processing_cauris <- function(file_in,
                                   lab_site_ids,
                                   control_strings = c("NEG", "AUR", "NTC", "EXT"),
                                   pos_rows = data.frame(Samples = c("AUR", "AUR"),
                                                         Targets = c("CAUR", "CJEJ")),
                                   con_rows = data.frame(Samples = c("AUR", "EXT", "NEG", "NTC", "AUR", "EXT", "NEG", "NTC"),
                                                         Targets = c("CAUR", "CAUR", "CAUR", "CAUR", "CJEJ", "CJEJ", "CJEJ", "CJEJ")),

                                   e_w_c = 3){

    auris1 <- w0110_sample_name_edits(file_in)


    # e track
    auris1_c <- w0150_sample_naming_structure(auris1,
                                              lab_site_ids,
                                              control_strings)

    error_line <- c("w0150")
    error_val <- c(auris1_c[2][[1]])

    auris1_c <- w0200_accepted_droplet_count(auris1_c[1][[1]], 10000)

    # e track
    auris1_c <- w0300_ntc_control_check(auris1_c)

    error_line <- c(error_line, "w0300")
    error_val <- c(error_val, auris1_c[2][[1]])

    # e track
    error_line <- c(error_line, "w0400")
    error_val <- c(error_val, w0400_pos_control_hard_stop(auris1_c[1][[1]], pos_rows))

    auris1_d <- w0450_pos_control_breakdown_check(auris1_c[1][[1]], pos_rows)

    # e track
    auris1_e <- w0600_ext_neg_control_check(auris1_d, ext_well_count = e_w_c,
                                            neg_well_count = 3,
                                            positive_droplet = 3,
                                            wells_over = 1)
    error_line <- c(error_line, "w0600")
    error_val <- c(error_val, auris1_e[2][[1]])

    # e track
    error_line <- c(error_line, "w0650")
    error_val <- c(error_val, w0650_cumulative_count_check(auris1_e[1][[1]]))

    auris1_f <- w0700_pos_droplet_sum(auris1_e[1][[1]], 4, con_rows)

    auris1_g <- w1000_remove_rows_as_chosen(auris1_f, c(2, 3, 6))

    error_df <- data.frame(error_line, error_val)

    message("End wrapper for C. auris.")

    return(list(auris1_g, error_df))
}
